### ISSUE TITLE
Pythnet RPC give 404 error

### ISSUE THREAD

**Issue by galvarado** [pyth-network/documentation#170]
During the installation process of [Hermes](https://github.com/pyth-network/pyth-crosschain/tree/main/hermes), there is a reference to obtaining instructions for setting up a Pythnet RPC instance from a node provider. However, when attempting to access the relevant information through the menu provided at https://docs.pyth.network/price-feeds/api-instances-and-providers, the specific option for "Pythnet RPC" leads to a [404 error](https://docs.pyth.network/price-feeds/api-instances-and-providers/pythnet-rpc)  indicating that the page or resource cannot be found. 
 
It is currently unclear where users can access information about providers offering Pythnet RPC instances. This lack of accessible information may present a challenge for individuals seeking to set up Pythnet RPC instances for their Hermes installation.

**Comment by guibescos** [comment]
Thanks so much for reporting, this has been fixed now!
