### ISSUE TITLE
Staking pyth

### ISSUE THREAD

**Issue by Kompart** [pyth-network/documentation#213]
How do I stake pyth? It's unclear to me how this should work.

**Comment by aditya520** [comment]
Hey @Kompart 

You can go to [Staking Pyth](https://staking.pyth.network/) to stake you PYTH tokens.

For more information, have a look at our [guide](https://pyth.network/blog/pyth-governance-a-guide-to-staking-pyth-tokens) to stake and unstake PYTH tokens.
