### ISSUE TITLE
Transaction reverted during simulation

### ISSUE THREAD

**Issue by Aitor0504** [pyth-network/documentation#221]
I have a problem when I try to stake more Pyth. I enter the amount I want to stake, click stake and Phantom window appear to approve the transaction. However, there is a message that says "Transaction reverted during simulation". It appears for a month and I can't stake more Pyth.
I have staked around 206 Pyth, I have funds in my account both from Sol and Pyth.
I hope you tell me a solution for this problem.
![Captura de pantalla 2024-03-19 151105](https://github.com/pyth-network/documentation/assets/125999949/2658cbb7-136a-42c0-bd75-4481bba02a62)

**Comment by guibescos** [comment]
Hi,

There's a technical limit to how many times you can stake in a row (without unstaking).

To get more help, please go to our Discord.
