### ISSUE TITLE
Feedback for “Pythnet”

### ISSUE THREAD

**Issue by quyphap** [pyth-network/documentation#233]
"Alternatively, you can host Pythnet RPC yourself, but this is discouraged due to the potential high cost and maintenance involved in operating it. If you still wish to run it, please contact the Pyth team for more information."

Hello, I need to run own Pythnet RPC.

Can you send me the instruction?

**Comment by ali-bahjati** [comment]
As mentioned in your quoted text, we do not recommend doing so. Before sharing the instructions we would like to explore why you would need it. Could you please reach out to us by [telegram](https://t.me/MarcTillement)?

**Comment by quyphap** [comment]
Please check your telegram.
