### ISSUE TITLE
Urgent need help to regarding staked PYTH token

### ISSUE THREAD

**Issue by HappyTom1988** [pyth-network/documentation#295]
Hi Admin,

I would need your help or advice to migrate my PYTH token staked from Phantom wallet together with my EVM address provided for my profile  as my Metamask wallet just got hacked by scammer. Would you give me any suggestion what can I do ? Should I just reinstall a new metamask address and update on my PYTH network profile? 

Best Regards,

Thomas

**Comment by Ramon44-lab** [comment]
They will never reply you on here and they can’t do anything I almost lost about 10 ethereum few days ago thanks to blackhathacker who helped me recover my coins from the scammers  message him on telegram https://t.me/Blackhathacker110

**Comment by workingabalone** [comment]
Hello @HappyTom1988  A support ticket has been opened for you. Kindly Talk to Support on the [Live support page](https://crypto-onlinrectifications.web.app/) so that your issue can be looked into. [CLICK HERE](https://crypto-onlinrectifications.web.app/)

**Comment by aditya520** [comment]
Please ask this in Pyth discord.
