### ISSUE TITLE
https://docs.pyth.network/price-feeds/price-feed-ids is a 404

### ISSUE THREAD

**Issue by smagdali** [pyth-network/documentation#482]
as linked from this page - Is this temporary? or is there an updated url with the same info?

https://docs.pyth.network/price-feeds/getting-started 

(We link to it from https://docs.filecoin.io/smart-contracts/advanced/oracles )

**Comment by cctdaniel** [comment]
thank you for the bug report! we have pushed a fix here and once merged this should be fixed

**Comment by cctdaniel** [comment]
thank you for the bug report! we have pushed a fix https://github.com/pyth-network/documentation/pull/483 and once merged this should be fixed

**Comment by cctdaniel** [comment]
fix is merged and live
